import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { ArrowUpDown } from "lucide-react";
import { toast } from "@/hooks/use-toast";

type Feedback = {
  id: string; // UUID generated by DB
  userId: string;
  fromBrandId: string;
  toBrandId: string;
  url?: string;
  message: string;
  isPublic: boolean;
  status: "PENDING" | "APPROVED" | "REJECTED";
  moderatorId?: string; // Optional, as it may not be set until moderation
  moderatorNotes?: string; // Optional
  approvedAt?: Date; // Optional, set when approved
  createdAt: Date; // Set by DB with defaultNow()
};

interface FeedbackResponse {
  feedbacks: Feedback[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// Fetch feedbacks with filters, sorting, and search
const fetchFeedbacks = async (
  page: number,
  limit: number,
  status?: string,
  search?: string,
  sort: "asc" | "desc" = "desc"
): Promise<FeedbackResponse> => {
  const params = new URLSearchParams({
    page: page.toString(),
    limit: limit.toString(),
    sort,
  });
  if (status) params.append("status", status);
  if (search) params.append("search", search);

  const response = await fetch(`/api/feedbacks?${params}`);
  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.error || "Failed to fetch feedbacks");
  }
  return response.json();
};

export default function ModeratorFeedbackPage() {
  const [page, setPage] = useState(1);
  const [statusFilter, setStatusFilter] = useState<string | undefined>(
    undefined
  );
  const [search, setSearch] = useState("");
  const [sort, setSort] = useState<"asc" | "desc">("desc");
  const limit = 10; // Smaller limit for mobile-friendliness

  const { data, isLoading, error } = useQuery({
    queryKey: ["feedbacks", page, limit, statusFilter, search, sort],
    queryFn: () => fetchFeedbacks(page, limit, statusFilter, search, sort),

    // keepPreviousData: true, // Smooth transitions during pagination/filtering
  });

  const handleSortToggle = () => {
    setSort((prev) => (prev === "asc" ? "desc" : "asc"));
  };

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearch(e.target.value);
    setPage(1); // Reset to first page on search
  };

  if (error) {
    toast({
      title: "Error",
      description: (error as Error).message,
      variant: "destructive",
    });
  }

  return (
    <div className="container mx-auto p-4 sm:p-6 max-w-4xl">
      <Card className="shadow-lg">
        <CardHeader className="pb-4">
          <CardTitle className="text-xl sm:text-2xl font-bold">
            Moderator Feedback Panel
          </CardTitle>
          <p className="text-sm text-gray-500">
            View user-submitted feedback (read-only)
          </p>
        </CardHeader>
        <CardContent>
          {/* Filters and Search */}
          <div className="flex flex-col sm:flex-row gap-4 mb-6">
            {/* <Select
              value={statusFilter || ""}
              onValueChange={(value) => {
                setStatusFilter(value || undefined);
                setPage(1);
              }}
            >
              <SelectTrigger className="w-full sm:w-40">
                <SelectValue placeholder="Filter by Status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="">All Statuses</SelectItem>
                <SelectItem value="PENDING">Pending</SelectItem>
                <SelectItem value="APPROVED">Approved</SelectItem>
                <SelectItem value="REJECTED">Rejected</SelectItem>
              </SelectContent>
            </Select> */}
            <Input
              placeholder="Search by message..."
              value={search}
              onChange={handleSearchChange}
              className="w-full sm:w-64"
            />
            <Button
              variant="outline"
              onClick={handleSortToggle}
              className="w-full sm:w-auto flex items-center gap-2"
            >
              <ArrowUpDown className="h-4 w-4" />
              <span className="hidden sm:inline">
                Sort by Date ({sort === "asc" ? "Oldest" : "Newest"})
              </span>
              <span className="sm:hidden">Sort</span>
            </Button>
          </div>

          {/* Feedback List */}
          {isLoading ? (
            <div className="space-y-4">
              {[...Array(5)].map((_, i) => (
                <Skeleton key={i} className="h-32 w-full rounded-lg" />
              ))}
            </div>
          ) : (
            <div className="space-y-4">
              {data && data.feedbacks.length === 0 && (
                <p className="text-center text-gray-500">No feedback found.</p>
              )}
              {data &&
                data.feedbacks.map((feedback) => (
                  <Card key={feedback.id} className="p-4">
                    <div className="flex flex-col gap-2">
                      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start">
                        <div>
                          <h3 className="font-semibold text-base sm:text-lg">
                            From: {feedback.fromBrandId} → To:{" "}
                            {feedback.toBrandId}
                          </h3>
                          <p className="text-sm text-gray-600 mt-1 line-clamp-3">
                            {feedback.message}
                          </p>
                          {feedback.url && (
                            <a
                              href={feedback.url}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="text-blue-500 text-sm underline break-all"
                            >
                              {feedback.url}
                            </a>
                          )}
                        </div>
                        <div className="mt-2 sm:mt-0 sm:text-right">
                          <Badge
                            variant={
                              feedback.status === "APPROVED"
                                ? "default"
                                : feedback.status === "REJECTED"
                                ? "destructive"
                                : "default"
                            }
                          >
                            {feedback.status}
                          </Badge>
                          <p className="text-xs text-gray-500 mt-1">
                            {new Date(feedback.createdAt).toLocaleDateString()}
                          </p>
                        </div>
                      </div>
                    </div>
                  </Card>
                ))}
            </div>
          )}

          {/* Pagination */}
          {data && data.pagination.totalPages > 1 && (
            <div className="flex justify-between items-center mt-6">
              <Button
                variant="outline"
                onClick={() => setPage((prev) => Math.max(prev - 1, 1))}
                disabled={page === 1 || isLoading}
                className="w-full sm:w-auto"
              >
                Previous
              </Button>
              <span className="text-sm">
                Page {page} of {data.pagination.totalPages}
              </span>
              <Button
                variant="outline"
                onClick={() =>
                  setPage((prev) =>
                    Math.min(prev + 1, data.pagination.totalPages)
                  )
                }
                disabled={page === data.pagination.totalPages || isLoading}
                className="w-full sm:w-auto"
              >
                Next
              </Button>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}